name: Django CI

on: [push]

env:
  DATABASE_URL: 'postgres://postgres:postgres@127.0.0.1:5432/github_actions'


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: float_tha_backend_senior
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test app
    - name: Lint
      run: |
        pip install flake8
        flake8 --exclude '.git,env/,*migrations*,*__init__*' --max-line-length 119 --ignore=F841,W504,E126,E121